plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

group = 'com.nodedistro'
version = '2.0.0'

base {
    archivesName = 'TNT-Hopper-Protect-Forge'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

minecraft {
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:26.1.2-64.1.2')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}
